### ISSUE TITLE
双类型谱面的歌曲，从最近动态进入歌曲详情时，未进入对应谱面而统一进入标准谱

### ISSUE THREAD

**Issue by xian2xian2** [Louiswu2011/chafenqi-android#3]
无论是先有标准后有 DX，亦或反过来，进入的都是标准谱的详情
以下例子：
VIIIbit Explorer
11235 | DX | Splash PLUS (2022)
1235 | STD | FESTiVAL (2023)

深海少女
315 | STD | GreeN PLUS
10315 | DX | FESTiVAL PLUS (2024)

https://github.com/Louiswu2011/chafenqi-android/assets/12865009/69ca433e-6d89-4514-b03f-e9388690650d

App 版本 1.0.10 (519)

**Comment by Louiswu2011** [comment]
fixed in 5af772b
